services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job_search_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    networks:
      - job_search_network

  nginx:
    image: nginx:alpine
    container_name: job_search_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - job_search_network

  mysql:
    image: mysql:5.7
    container_name: job_search_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: job_search
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - job_search_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: job_search_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - job_search_network

volumes:
  mysql_data:

networks:
  job_search_network:
    driver: bridge
